### PR TITLE
UE5.1 support

### PR DESCRIPTION
**Pull request by sleeptightAnsiC**
- change header include: "Dialogs/CustomDialog.h" to "Dialog/SCustomDialog.h"
- add Private Dependency:  "ToolWidgets"

### CODE REVIEW

**Comment by sleeptightAnsiC** [comment]
In 5.1, compilation fails due to missing "Dialogs/CustomDialog.h". It seems like they just renamed it to "Dialog/SCustomDialog.h".
Also, I had to add a module used in SCustomDialog.h ("ToolWidgets"), as I was getting Linker errors.
Not sure if these changes allow plugin to work properly, and if there is anything else missing, but for me it just works fine.

**Comment by nachomonkey** [comment]
Alright I'm looking into it

**Comment by nachomonkey** [comment]
It worked properly except the dialog that pops up for failed BP compilation, which now didn't have any content. Anyway, I fixed that, along with about ten other changes to fix deprecation problems. Now it works cleanly and smoothly, I think ;)

**Comment by nachomonkey** [comment]
And thank you- sorry for letting it break :open_mouth:

**Comment by sleeptightAnsiC** [comment]
No problem.
I also seen the deprecated warnings and one failed ensure on my side, but I just wanted my project to compile,
so good to hear that You've already taken care of everything.

**Pull request merged**
